name: Compile on multiple Java versions

on:
  push:
    branches:
      - xci
  pull_request:
    branches-ignore:
      - '**'

jobs:

  build:
    name: Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 14, 13, 12, 11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Check Java version
        run: java -version

      - name: Install all components
        run: mvn -B -DskipTests=true install

      - name: Test pdq common
        run: |
          mvn -B -Dpdq.skip-tests="**/*Postgres.java" test -f common

      - name: Test pdq datasources
        run: |
          mvn -B -Dpdq.skip-tests="**/*Postgres.java" test -f datasources

#      - name: Test pdq reasoning
#        run: |
#          mvn -B -Dpdq.skip-tests="**/*Postgres.java" test -f reasoning

      - name: Test pdq cost
        run: |
          mvn -B -Dpdq.skip-tests="**/*Postgres.java" test -f cost
