name: tmate

on:
  push:
    branches:
      - ci
  pull_request:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: pdq

        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Install pdq common
        run: |
          mvn -B install -DskipTests -f common

      - name: Install pdq common
        run: |
          mvn -B test -f common
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
